import { getTranslations } from 'next-intl/server';

import { Tab } from '@/shared/types/blocks/common';

export interface Setting {
  name: string;
  title: string;
  type: string;
  placeholder?: string;
  options?: {
    title: string;
    value: string;
  }[];
  tip?: string;
  value?: string | string[] | boolean | number;
  group?: string;
  tab?: string;
  attributes?: Record<string, any>;
}

export interface SettingGroup {
  name: string;
  title: string;
  description?: string;
  tab: string;
}

export async function getSettingTabs(tab: string) {
  const t = await getTranslations('admin.settings');

  const tabs: Tab[] = [
    {
      name: 'general',
      title: t('edit.tabs.general'),
      url: '/admin/settings/general',
      is_active: tab === 'general',
    },
    {
      name: 'auth',
      title: t('edit.tabs.auth'),
      url: '/admin/settings/auth',
      is_active: tab === 'auth',
    },
    {
      name: 'payment',
      title: t('edit.tabs.payment'),
      url: '/admin/settings/payment',
      is_active: tab === 'payment',
    },
    {
      name: 'email',
      title: t('edit.tabs.email'),
      url: '/admin/settings/email',
      is_active: tab === 'email',
    },
    {
      name: 'storage',
      title: t('edit.tabs.storage'),
      url: '/admin/settings/storage',
      is_active: tab === 'storage',
    },

    {
      name: 'ai',
      title: t('edit.tabs.ai'),
      url: '/admin/settings/ai',
      is_active: tab === 'ai',
    },
    {
      name: 'analytics',
      title: t('edit.tabs.analytics'),
      url: '/admin/settings/analytics',
      is_active: tab === 'analytics',
    },
    {
      name: 'ads',
      title: t('edit.tabs.ads'),
      url: '/admin/settings/ads',
      is_active: tab === 'ads',
    },
    {
      name: 'affiliate',
      title: t('edit.tabs.affiliate'),
      url: '/admin/settings/affiliate',
      is_active: tab === 'affiliate',
    },
    {
      name: 'customer_service',
      title: t('edit.tabs.customer_service'),
      url: '/admin/settings/customer_service',
      is_active: tab === 'customer_service',
    },
  ];

  return tabs;
}

export async function getSettingGroups() {
  const t = await getTranslations('admin.settings');
  const settingGroups: SettingGroup[] = [
    {
      name: 'appinfo',
      title: t('groups.appinfo'),
      description: t('groups.appinfo_description'),
      tab: 'general',
    },
    {
      name: 'user_role',
      title: t('groups.user_role'),
      description: t('groups.user_role_description'),
      tab: 'general',
    },
    {
      name: 'credit',
      title: t('groups.credit'),
      description: t('groups.credit_description'),
      tab: 'general',
    },
    {
      name: 'email_auth',
      title: t('groups.email_auth'),
      description: t('groups.email_auth_description'),
      tab: 'auth',
    },
    {
      name: 'google_auth',
      title: t('groups.google_auth'),
      description: t('groups.google_auth_description'),
      tab: 'auth',
    },
    {
      name: 'github_auth',
      title: t('groups.github_auth'),
      description: t('groups.github_auth_description'),
      tab: 'auth',
    },
    {
      name: 'basic_payment',
      title: t('groups.basic_payment'),
      description: t('groups.basic_payment_description'),
      tab: 'payment',
    },
    {
      name: 'stripe',
      title: t('groups.stripe'),
      description: t.raw('groups.stripe_description'),
      tab: 'payment',
    },
    {
      name: 'creem',
      title: t('groups.creem'),
      description: t.raw('groups.creem_description'),
      tab: 'payment',
    },
    {
      name: 'paypal',
      title: t('groups.paypal'),
      description: t('groups.paypal_description'),
      tab: 'payment',
    },
    {
      name: 'google_analytics',
      title: t('groups.google_analytics'),
      description: t.raw('groups.google_analytics_description'),
      tab: 'analytics',
    },
    {
      name: 'clarity',
      title: t('groups.clarity'),
      description: t.raw('groups.clarity_description'),
      tab: 'analytics',
    },
    {
      name: 'plausible',
      title: t('groups.plausible'),
      description: t.raw('groups.plausible_description'),
      tab: 'analytics',
    },
    {
      name: 'openpanel',
      title: t('groups.openpanel'),
      description: t.raw('groups.openpanel_description'),
      tab: 'analytics',
    },
    {
      name: 'vercel_analytics',
      title: t('groups.vercel_analytics'),
      description: t.raw('groups.vercel_analytics_description'),
      tab: 'analytics',
    },
    {
      name: 'resend',
      title: t('groups.resend'),
      description: t('groups.resend_description'),
      tab: 'email',
    },
    {
      name: 'r2',
      title: t('groups.r2'),
      description: t('groups.r2_description'),
      tab: 'storage',
    },
    {
      name: 'openrouter',
      title: t('groups.openrouter'),
      description: t.raw('groups.openrouter_description'),
      tab: 'ai',
    },
    {
      name: 'replicate',
      title: t('groups.replicate'),
      description: t.raw('groups.replicate_description'),
      tab: 'ai',
    },
    {
      name: 'fal',
      title: 'Fal',
      description: t.raw('groups.fal_description'),
      tab: 'ai',
    },
    {
      name: 'gemini',
      title: 'Gemini',
      description: t.raw('groups.gemini_description'),
      tab: 'ai',
    },
    {
      name: 'kie',
      title: 'Kie',
      description: t.raw('groups.kie_description'),
      tab: 'ai',
    },
    {
      name: 'adsense',
      title: t('groups.adsense'),
      description: t('groups.adsense_description'),
      tab: 'ads',
    },
    {
      name: 'affonso',
      title: t('groups.affonso'),
      description: t.raw('groups.affonso_description'),
      tab: 'affiliate',
    },
    {
      name: 'promotekit',
      title: t('groups.promotekit'),
      description: t.raw('groups.promotekit_description'),
      tab: 'affiliate',
    },
    {
      name: 'crisp',
      title: t('groups.crisp'),
      description: t.raw('groups.crisp_description'),
      tab: 'customer_service',
    },
    {
      name: 'tawk',
      title: t('groups.tawk'),
      description: t.raw('groups.tawk_description'),
      tab: 'customer_service',
    },
  ];
  return settingGroups;
}

export async function getSettings() {
  const t = await getTranslations('admin.settings.definitions');
  const settings: Setting[] = [
    {
      name: 'app_name',
      title: t('app_name.title'),
      placeholder: 'Nanobanana Joyflix',
      type: 'text',
      group: 'appinfo',
      tab: 'general',
    },
    {
      name: 'app_description',
      title: t('app_description.title'),
      placeholder:
        'Nanobanana Joyflix is a flagship AI visual creation platform.',
      type: 'textarea',
      group: 'appinfo',
      tab: 'general',
    },
    {
      name: 'app_logo',
      title: t('app_logo.title'),
      type: 'upload_image',
      group: 'appinfo',
      tab: 'general',
    },
    {
      name: 'app_preview_image',
      title: t('app_preview_image.title'),
      type: 'upload_image',
      group: 'appinfo',
      tab: 'general',
    },
    {
      name: 'initial_role_enabled',
      title: t('initial_role_enabled.title'),
      type: 'switch',
      value: 'false',
      group: 'user_role',
      tab: 'general',
      tip: t('initial_role_enabled.tip'),
    },
    {
      name: 'initial_role_name',
      title: t('initial_role_name.title'),
      type: 'select',
      value: 'viewer',
      options: [
        { title: t('initial_role_name.options.viewer'), value: 'viewer' },
        { title: t('initial_role_name.options.editor'), value: 'editor' },
        { title: t('initial_role_name.options.admin'), value: 'admin' },
        { title: t('initial_role_name.options.super_admin'), value: 'super_admin' },
      ],
      group: 'user_role',
      tab: 'general',
      tip: t('initial_role_name.tip'),
    },
    {
      name: 'initial_credits_enabled',
      title: t('initial_credits_enabled.title'),
      type: 'switch',
      value: 'false',
      group: 'credit',
      tab: 'general',
      tip: t('initial_credits_enabled.tip'),
    },
    {
      name: 'initial_credits_amount',
      title: t('initial_credits_amount.title'),
      type: 'number',
      placeholder: '0',
      group: 'credit',
      tab: 'general',
      tip: t('initial_credits_amount.tip'),
    },
    {
      name: 'initial_credits_valid_days',
      title: t('initial_credits_valid_days.title'),
      type: 'number',
      placeholder: '30',
      group: 'credit',
      tab: 'general',
      tip: t('initial_credits_valid_days.tip'),
    },
    {
      name: 'initial_credits_description',
      title: t('initial_credits_description.title'),
      type: 'text',
      placeholder: t('initial_credits_description.placeholder'),
      group: 'credit',
      tab: 'general',
      tip: t('initial_credits_description.tip'),
    },
    {
      name: 'email_auth_enabled',
      title: t('email_auth_enabled.title'),
      type: 'switch',
      value: 'true',
      group: 'email_auth',
      tab: 'auth',
      tip: t.has('email_auth_enabled.tip') ? t('email_auth_enabled.tip') : undefined,
    },
    {
      name: 'email_verification_enabled',
      title: t('email_verification_enabled.title'),
      type: 'switch',
      value: 'false',
      group: 'email_auth',
      tab: 'auth',
      tip: t('email_verification_enabled.tip'),
    },
    {
      name: 'google_auth_enabled',
      title: t('google_auth_enabled.title'),
      type: 'switch',
      value: 'false',
      group: 'google_auth',
      tab: 'auth',
    },
    {
      name: 'google_one_tap_enabled',
      title: t('google_one_tap_enabled.title'),
      type: 'switch',
      value: 'false',
      group: 'google_auth',
      tab: 'auth',
      tip: t('google_one_tap_enabled.tip'),
    },
    {
      name: 'google_client_id',
      title: t('google_client_id.title'),
      type: 'text',
      placeholder: '',
      group: 'google_auth',
      tab: 'auth',
    },
    {
      name: 'google_client_secret',
      title: t('google_client_secret.title'),
      type: 'password',
      placeholder: '',
      group: 'google_auth',
      tab: 'auth',
    },
    {
      name: 'github_auth_enabled',
      title: t('github_auth_enabled.title'),
      type: 'switch',
      group: 'github_auth',
      tab: 'auth',
    },
    {
      name: 'github_client_id',
      title: t('github_client_id.title'),
      type: 'text',
      placeholder: '',
      group: 'github_auth',
      tab: 'auth',
    },
    {
      name: 'github_client_secret',
      title: t('github_client_secret.title'),
      type: 'password',
      placeholder: '',
      group: 'github_auth',
      tab: 'auth',
    },
    {
      name: 'select_payment_enabled',
      title: t('select_payment_enabled.title'),
      type: 'switch',
      value: 'false',
      tip: t('select_payment_enabled.tip'),
      placeholder: '',
      group: 'basic_payment',
      tab: 'payment',
    },
    {
      name: 'default_payment_provider',
      title: t('default_payment_provider.title'),
      type: 'select',
      value: 'stripe',
      options: [
        {
          title: t('default_payment_provider.options.stripe'),
          value: 'stripe',
        },
        {
          title: t('default_payment_provider.options.creem'),
          value: 'creem',
        },
        {
          title: t('default_payment_provider.options.paypal'),
          value: 'paypal',
        },
      ],
      tip: t('default_payment_provider.tip'),
      group: 'basic_payment',
      tab: 'payment',
    },
    {
      name: 'stripe_enabled',
      title: t('stripe_enabled.title'),
      type: 'switch',
      value: 'false',
      placeholder: '',
      group: 'stripe',
      tab: 'payment',
    },
    {
      name: 'stripe_publishable_key',
      title: t('stripe_publishable_key.title'),
      type: 'text',
      placeholder: 'pk_xxx',
      group: 'stripe',
      tab: 'payment',
    },
    {
      name: 'stripe_secret_key',
      title: t('stripe_secret_key.title'),
      type: 'password',
      placeholder: 'sk_xxx',
      group: 'stripe',
      tab: 'payment',
    },
    {
      name: 'stripe_signing_secret',
      title: t('stripe_signing_secret.title'),
      type: 'password',
      placeholder: 'whsec_xxx',
      tip: t('stripe_signing_secret.tip'),
      group: 'stripe',
      tab: 'payment',
    },
    {
      name: 'stripe_payment_methods',
      title: t('stripe_payment_methods.title'),
      type: 'checkbox',
      tip: t('stripe_payment_methods.tip'),
      options: [
        { title: t('stripe_payment_methods.options.card'), value: 'card' },
        { title: t('stripe_payment_methods.options.wechat_pay'), value: 'wechat_pay' },
        { title: t('stripe_payment_methods.options.alipay'), value: 'alipay' },
      ],
      value: ['card'],
      group: 'stripe',
      tab: 'payment',
    },
    {
      name: 'stripe_promotion_codes',
      title: t('stripe_promotion_codes.title'),
      type: 'textarea',
      attributes: {
        rows: 6,
      },
      placeholder: `{
  "starter": "promo_xxx",
  "standard-monthly": "promo_xxx",
  "premium-yearly": "promo_xxx"
}`,
      group: 'stripe',
      tab: 'payment',
      tip: t.raw('stripe_promotion_codes.tip'),
    },
    {
      name: 'stripe_allow_promotion_codes',
      title: t('stripe_allow_promotion_codes.title'),
      type: 'switch',
      value: 'false',
      group: 'stripe',
      tab: 'payment',
      tip: t('stripe_allow_promotion_codes.tip'),
    },
    {
      name: 'creem_enabled',
      title: t('creem_enabled.title'),
      type: 'switch',
      value: 'false',
      group: 'creem',
      tab: 'payment',
    },
    {
      name: 'creem_environment',
      title: t('creem_environment.title'),
      type: 'select',
      value: 'sandbox',
      options: [
        { title: t('creem_environment.options.sandbox'), value: 'sandbox' },
        { title: t('creem_environment.options.production'), value: 'production' },
      ],
      group: 'creem',
      tab: 'payment',
    },
    {
      name: 'creem_api_key',
      title: t('creem_api_key.title'),
      type: 'password',
      placeholder: 'creem_xxx',
      group: 'creem',
      tab: 'payment',
    },
    {
      name: 'creem_signing_secret',
      title: t('creem_signing_secret.title'),
      type: 'password',
      placeholder: 'whsec_xxx',
      group: 'creem',
      tab: 'payment',
      tip: t('creem_signing_secret.tip'),
    },
    {
      name: 'creem_product_ids',
      title: t('creem_product_ids.title'),
      type: 'textarea',
      attributes: {
        rows: 6,
      },
      placeholder: `{
  "starter": "prod_xxx",
  "standard-monthly": "prod_xxx",
  "premium-yearly": "prod_xxx"
}`,
      group: 'creem',
      tab: 'payment',
      tip: t.raw('creem_product_ids.tip'),
    },
    {
      name: 'paypal_enabled',
      title: t('paypal_enabled.title'),
      type: 'switch',
      value: 'false',
      group: 'paypal',
      tab: 'payment',
    },
    {
      name: 'paypal_environment',
      title: t('paypal_environment.title'),
      type: 'select',
      value: 'sandbox',
      options: [
        { title: t('paypal_environment.options.sandbox'), value: 'sandbox' },
        { title: t('paypal_environment.options.production'), value: 'production' },
      ],
      group: 'paypal',
      tab: 'payment',
    },
    {
      name: 'paypal_client_id',
      title: t('paypal_client_id.title'),
      type: 'text',
      placeholder: 'paypal_xxx',
      group: 'paypal',
      tab: 'payment',
    },
    {
      name: 'paypal_client_secret',
      title: t('paypal_client_secret.title'),
      type: 'password',
      placeholder: 'paypal_xxx',
      group: 'paypal',
      tab: 'payment',
    },
    {
      name: 'paypal_webhook_id',
      title: t('paypal_webhook_id.title'),
      type: 'text',
      placeholder: 'xxx',
      tip: t('paypal_webhook_id.tip'),
      group: 'paypal',
      tab: 'payment',
    },
    {
      name: 'google_analytics_id',
      title: t('google_analytics_id.title'),
      type: 'text',
      placeholder: '',
      group: 'google_analytics',
      tab: 'analytics',
    },
    {
      name: 'clarity_id',
      title: t('clarity_id.title'),
      type: 'text',
      placeholder: '',
      group: 'clarity',
      tab: 'analytics',
    },
    {
      name: 'plausible_domain',
      title: t('plausible_domain.title'),
      type: 'text',
      placeholder: 'shipany.site',
      group: 'plausible',
      tab: 'analytics',
    },
    {
      name: 'plausible_src',
      title: t('plausible_src.title'),
      type: 'url',
      placeholder: 'https://plausible.io/js/script.js',
      group: 'plausible',
      tab: 'analytics',
    },
    {
      name: 'openpanel_client_id',
      title: t('openpanel_client_id.title'),
      type: 'text',
      placeholder: '',
      group: 'openpanel',
      tab: 'analytics',
    },
    {
      name: 'vercel_analytics_enabled',
      title: t('vercel_analytics_enabled.title'),
      type: 'switch',
      value: 'false',
      group: 'vercel_analytics',
      tab: 'analytics',
    },
    {
      name: 'resend_api_key',
      title: t('resend_api_key.title'),
      type: 'password',
      placeholder: '',
      group: 'resend',
      tab: 'email',
    },
    {
      name: 'resend_sender_email',
      title: t('resend_sender_email.title'),
      type: 'text',
      placeholder: 'Nanobanana Joyflix <no-reply@mail.nanobanana-joyflix.ai>',
      group: 'resend',
      tab: 'email',
    },
    {
      name: 'r2_access_key',
      title: t('r2_access_key.title'),
      type: 'text',
      placeholder: '',
      group: 'r2',
      tab: 'storage',
    },
    {
      name: 'r2_secret_key',
      title: t('r2_secret_key.title'),
      type: 'password',
      placeholder: '',
      group: 'r2',
      tab: 'storage',
    },
    {
      name: 'r2_bucket_name',
      title: t('r2_bucket_name.title'),
      type: 'text',
      placeholder: '',
      group: 'r2',
      tab: 'storage',
    },
    {
      name: 'r2_upload_path',
      title: t('r2_upload_path.title'),
      type: 'text',
      placeholder: 'uploads',
      tip: t('r2_upload_path.tip'),
      group: 'r2',
      tab: 'storage',
    },
    {
      name: 'r2_endpoint',
      title: t('r2_endpoint.title'),
      type: 'url',
      placeholder: 'https://<account-id>.r2.cloudflarestorage.com',
      tip: t('r2_endpoint.tip'),
      group: 'r2',
      tab: 'storage',
    },
    {
      name: 'r2_domain',
      title: t('r2_domain.title'),
      type: 'url',
      placeholder: '',
      group: 'r2',
      tab: 'storage',
    },
    {
      name: 'openrouter_api_key',
      title: t('openrouter_api_key.title'),
      type: 'password',
      placeholder: 'sk-or-xxx',
      group: 'openrouter',
      tab: 'ai',
    },
    {
      name: 'openrouter_base_url',
      title: t('openrouter_base_url.title'),
      type: 'url',
      placeholder: 'https://openrouter.ai/api/v1',
      tip: t('openrouter_base_url.tip'),
      group: 'openrouter',
      tab: 'ai',
    },
    {
      name: 'replicate_api_token',
      title: t('replicate_api_token.title'),
      type: 'password',
      placeholder: 'r8_xxx',
      group: 'replicate',
      tab: 'ai',
    },
    {
      name: 'replicate_custom_storage',
      title: t('replicate_custom_storage.title'),
      type: 'switch',
      value: 'false',
      group: 'replicate',
      tab: 'ai',
      tip: t('replicate_custom_storage.tip'),
    },
    {
      name: 'fal_api_key',
      title: t('fal_api_key.title'),
      type: 'password',
      placeholder: 'fal_xxx',
      group: 'fal',
      tip: t('fal_api_key.tip'),
      tab: 'ai',
    },
    {
      name: 'fal_custom_storage',
      title: t('fal_custom_storage.title'),
      type: 'switch',
      value: 'false',
      group: 'fal',
      tab: 'ai',
      tip: t('fal_custom_storage.tip'),
    },
    {
      name: 'gemini_api_key',
      title: t('gemini_api_key.title'),
      type: 'password',
      placeholder: 'AIza...',
      group: 'gemini',
      tip: t('gemini_api_key.tip'),
      tab: 'ai',
    },
    {
      name: 'kie_api_key',
      title: t('kie_api_key.title'),
      type: 'password',
      placeholder: 'xxx',
      group: 'kie',
      tip: t('kie_api_key.tip'),
      tab: 'ai',
    },
    {
      name: 'kie_custom_storage',
      title: t('kie_custom_storage.title'),
      type: 'switch',
      value: 'false',
      group: 'kie',
      tab: 'ai',
      tip: t('kie_custom_storage.tip'),
    },
    {
      name: 'adsense_code',
      title: t('adsense_code.title'),
      type: 'text',
      placeholder: 'ca-pub-xxx',
      group: 'adsense',
      tab: 'ads',
    },
    {
      name: 'affonso_enabled',
      title: t('affonso_enabled.title'),
      type: 'switch',
      value: 'false',
      group: 'affonso',
      tab: 'affiliate',
    },
    {
      name: 'affonso_id',
      title: t('affonso_id.title'),
      type: 'text',
      placeholder: 'xxx',
      tip: t('affonso_id.tip'),
      group: 'affonso',
      tab: 'affiliate',
    },
    {
      name: 'affonso_cookie_duration',
      title: t('affonso_cookie_duration.title'),
      type: 'number',
      placeholder: '30',
      tip: t('affonso_cookie_duration.tip'),
      value: '30',
      group: 'affonso',
      tab: 'affiliate',
    },
    {
      name: 'promotekit_enabled',
      title: t('promotekit_enabled.title'),
      type: 'switch',
      value: 'false',
      group: 'promotekit',
      tab: 'affiliate',
    },
    {
      name: 'promotekit_id',
      title: t('promotekit_id.title'),
      type: 'text',
      placeholder: 'xxx',
      tip: t('promotekit_id.tip'),
      group: 'promotekit',
      tab: 'affiliate',
    },
    {
      name: 'crisp_enabled',
      title: t('crisp_enabled.title'),
      type: 'switch',
      value: 'false',
      group: 'crisp',
      tab: 'customer_service',
    },
    {
      name: 'crisp_website_id',
      title: t('crisp_website_id.title'),
      type: 'text',
      placeholder: 'xxx',
      group: 'crisp',
      tab: 'customer_service',
    },
    {
      name: 'tawk_enabled',
      title: t('tawk_enabled.title'),
      type: 'switch',
      value: 'false',
      group: 'tawk',
      tab: 'customer_service',
    },
    {
      name: 'tawk_property_id',
      title: t('tawk_property_id.title'),
      tip: t('tawk_property_id.tip'),
      type: 'text',
      placeholder: 'xxx',
      group: 'tawk',
      tab: 'customer_service',
    },
    {
      name: 'tawk_widget_id',
      title: t('tawk_widget_id.title'),
      type: 'text',
      placeholder: 'xxx',
      group: 'tawk',
      tab: 'customer_service',
    },
  ];

  return settings;
}

export const publicSettingNames = [
  'email_auth_enabled',
  'google_auth_enabled',
  'google_one_tap_enabled',
  'google_client_id',
  'github_auth_enabled',
  'select_payment_enabled',
  'default_payment_provider',
  'stripe_enabled',
  'creem_enabled',
  'paypal_enabled',
  'affonso_enabled',
  'promotekit_enabled',
  'crisp_enabled',
  'tawk_enabled',
];

export async function getAllSettingNames() {
  const settings = await getSettings();
  const settingNames: string[] = [];

  settings.forEach((setting: Setting) => {
    settingNames.push(setting.name);
  });

  return settingNames;
}
